### ISSUE TITLE
Unable to create new schema

### ISSUE THREAD

**Issue by AnsonT** [timgit/pg-boss#209]
Connecting to a version PostgreSQL 11.10, I'm getting errors from cannot execute in a read-only transaction.
I've confirmed with the same connection string with node client 'pg', that I'm able to create and drop tables, but pg-boss is giving this error.

(node:12) UnhandledPromiseRejectionWarning: error: cannot execute DELETE in a read-only transaction
    at Parser.parseErrorMessage (/home/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/app/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

**Comment by timgit** [comment]
That seems like an issue with the role you're using for your queries.  You need to have permission to delete records from the job table to move old jobs into the archive, for example.

**Comment by AnsonT** [comment]
Found the problem not connecting to pgpool.
