### ISSUE TITLE
Duplicate key value violates unique constraint: job_singleton_queue

### ISSUE THREAD

**Issue by tkambler** [timgit/pg-boss#522]
Could you help me understand what could possibly be causing this error to be emitted by PGBoss?

```
{
  "message": "duplicate key value violates unique constraint \"job_singleton_queue\"",
  "name": "error",
  "stack": "error: duplicate key value violates unique constraint \"job_singleton_queue\"\n    at /app/node_modules/pg/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Db.executeSql (/app/node_modules/pg-boss/src/db.js:28:14)\n    at Boss.executeSql (/app/node_modules/pg-boss/src/boss.js:249:14)\n    at Boss.expire (/app/node_modules/pg-boss/src/boss.js:216:5)\n    at Boss.onMaintenance (/app/node_modules/pg-boss/src/boss.js:132:7)\n    at resolveWithinSeconds (/app/node_modules/pg-boss/src/manager.js:35:14)\n    at /app/node_modules/pg-boss/node_modules/p-map/index.js:57:22",
  "code": "23505"
}
```

**Comment by timgit** [comment]
What version of pg-boss are you running?  This error should be resolved in the latest release

**Comment by ericholiveira** [comment]
Just as a note, i had the exact same problem and it was fixed updating the lib

**Comment by ericholiveira** [comment]
Unfortunately the problem persists... 
It was fixed when i updated the lib, but now is happening again even in the updated version

**Comment by timgit** [comment]
What version are you running?  The index you mentioned no longer exists.
